# Generated by Django 3.1.6 on 2021-03-25 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiem_nghiem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hinhanhlv0',
            name='level_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiem_nghiem.level0'),
        ),
        migrations.AlterField(
            model_name='hinhanhlv1',
            name='level_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiem_nghiem.level1'),
        ),
        migrations.AlterField(
            model_name='hinhanhlv2',
            name='level_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiem_nghiem.level2'),
        ),
        migrations.AlterField(
            model_name='hinhanhlv3',
            name='level_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiem_nghiem.level3'),
        ),
        migrations.AlterField(
            model_name='hinhanhlv4',
            name='level_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiem_nghiem.level4'),
        ),
        migrations.AlterField(
            model_name='hinhanhlv5',
            name='level_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiem_nghiem.level5'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='level_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiem_nghiem.level0', verbose_name='<-- Level0'),
        ),
        migrations.AlterField(
            model_name='level2',
            name='level_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiem_nghiem.level1', verbose_name='<-- Tiêu đề cấp 1'),
        ),
        migrations.AlterField(
            model_name='level3',
            name='level_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiem_nghiem.level2', verbose_name='<-- Tiêu đề cấp 2'),
        ),
        migrations.AlterField(
            model_name='level4',
            name='level_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiem_nghiem.level3', verbose_name='<-- Tiêu đề cấp 3'),
        ),
        migrations.AlterField(
            model_name='level5',
            name='level_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiem_nghiem.level4', verbose_name='<-- Tiêu đề cấp 4'),
        ),
    ]
