# Generated by Django 3.1.6 on 2021-03-19 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuocLieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tieng_viet', models.CharField(max_length=200, verbose_name='Tên tiếng việt')),
                ('ten_la_tinh', models.CharField(max_length=200, verbose_name='Tên Latinh')),
                ('ngay_dang', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày cập nhật')),
                ('nguoi_dang', models.CharField(blank=True, help_text='Tên tác giả, nếu không nhập thông tin chương trình sẽ mặc định là tên tài khoản.', max_length=200, null=True, verbose_name='người đăng')),
                ('slug', models.SlugField(allow_unicode=True, help_text='Thông tin này sẽ hiển thị tại địa chỉ web, ví dụ: www.home/duoclieu/toi-o-day', unique=True)),
            ],
            options={
                'verbose_name': 'Dược liệu',
                'verbose_name_plural': 'B. Dược liệu',
                'ordering': ['ten_tieng_viet'],
            },
        ),
        migrations.CreateModel(
            name='HoThucVat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('La_tinh', models.CharField(max_length=200, verbose_name='họ latinh')),
                ('Tieng_viet', models.CharField(max_length=200, verbose_name='họ tiếng việt')),
                ('gioi_thieu_chung', models.TextField(blank=True, max_length=1000, null=True, verbose_name='giới thiện chung')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'verbose_name': 'Họ thực vật',
                'verbose_name_plural': 'A. Họ thực vật',
                'ordering': ['Tieng_viet'],
            },
        ),
        migrations.CreateModel(
            name='Level1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='tiêu đề cấp 1')),
                ('noi_dung', models.TextField(blank=True, max_length=2000, null=True, verbose_name='nội dung')),
            ],
            options={
                'verbose_name': 'NHC/lv1',
                'verbose_name_plural': 'C.1 -->',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Level2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='tiêu đề cấp 2')),
                ('noi_dung', models.TextField(blank=True, max_length=2000, null=True, verbose_name='nội dung')),
                ('level_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.level1', verbose_name='<-- cấp 1')),
            ],
            options={
                'verbose_name': 'NHC/lv1/lv2',
                'verbose_name_plural': 'C.1.2 -->',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Level3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='tiêu đề cấp 3')),
                ('noi_dung', models.TextField(blank=True, max_length=2000, null=True, verbose_name='nội dung')),
                ('level_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.level2', verbose_name='<-- cấp 2')),
            ],
            options={
                'verbose_name': 'NHC/lv1/lv2/lv3',
                'verbose_name_plural': 'C.1.2.3 -->',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Level4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='tiêu đề cấp 4')),
                ('noi_dung', models.TextField(blank=True, max_length=2000, null=True, verbose_name='nội dung')),
                ('level_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.level3', verbose_name='<-- cấp 3')),
            ],
            options={
                'verbose_name': 'NHC/lv1/lv2/lv3/lv4',
                'verbose_name_plural': 'C.1.2.3.4 -->',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NhomHoatChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhom', models.CharField(max_length=200, verbose_name='tên nhóm')),
                ('dinh_nghia', models.TextField(blank=True, max_length=2000, null=True, verbose_name='định nghĩa')),
            ],
            options={
                'verbose_name': 'Nhóm hoạt chất',
                'verbose_name_plural': 'C = Nhóm hoạt chất',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ThanhPhanHoaHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thanh_phan_hoa_hoc', models.TextField(max_length=1000, verbose_name='thành phần hoá học')),
                ('duoc_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.duoclieu', verbose_name='dược liệu')),
            ],
            options={
                'verbose_name': 'thành phần hoá học',
                'verbose_name_plural': 'thành phần hoá học',
            },
        ),
        migrations.CreateModel(
            name='TenKhoaHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tieng_viet_spp', models.CharField(blank=True, max_length=200, null=True, verbose_name='tên tiếng việt spp')),
                ('ten_latinh_spp', models.CharField(blank=True, max_length=200, null=True, verbose_name='tên latinh spp')),
                ('duoc_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.duoclieu', verbose_name='dược liệu')),
            ],
            options={
                'verbose_name': 'tên khoa học spp',
                'verbose_name_plural': 'tên khoa học spp',
            },
        ),
        migrations.CreateModel(
            name='TacDungVaCongDung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tac_dung_va_cong_dung', models.TextField(max_length=1000, verbose_name='tác dụng và công dụng')),
                ('duoc_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.duoclieu', verbose_name='dược liệu')),
            ],
            options={
                'verbose_name': 'tác dụng và công dụng',
                'verbose_name_plural': 'tác dụng và công dụng',
            },
        ),
        migrations.CreateModel(
            name='Level5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de_5', models.CharField(blank=True, max_length=200, null=True, verbose_name='tiêu đề cấp 5')),
                ('noi_dung', models.TextField(blank=True, max_length=2000, null=True, verbose_name='nội dung')),
                ('level_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.level4', verbose_name='<-- cấp 4')),
            ],
            options={
                'verbose_name': 'NHC/lv1/lv2/lv3/lv4/lv5',
                'verbose_name_plural': 'C.1.2.4.5 -->',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='level1',
            name='nhom_hoat_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.nhomhoatchat', verbose_name='<-- Nhóm hoạt chất'),
        ),
        migrations.CreateModel(
            name='HinhAnhMinhHoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh_minh_hoa', models.ImageField(upload_to='duoclieu', verbose_name='hình ảnh minh hoạ')),
                ('duoc_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.duoclieu', verbose_name='dược liệu')),
            ],
            options={
                'verbose_name': 'hình ảnh minh hoạ',
                'verbose_name_plural': 'hình ảnh minh hoạ',
            },
        ),
        migrations.CreateModel(
            name='HinhAnhBoSung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh_bo_sung', models.ImageField(upload_to='duoclieu', verbose_name='hình ảnh bổ sung')),
                ('duoc_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.duoclieu', verbose_name='dược liệu')),
            ],
            options={
                'verbose_name': 'hình ảnh bổ sung',
                'verbose_name_plural': 'hình ảnh bổ sung',
            },
        ),
        migrations.CreateModel(
            name='GhiChu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghi_chu', models.TextField(max_length=1000, verbose_name='ghi chú')),
                ('duoc_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.duoclieu', verbose_name='dược liệu')),
            ],
            options={
                'verbose_name': 'ghi chú',
                'verbose_name_plural': 'ghi chú',
            },
        ),
        migrations.AddField(
            model_name='duoclieu',
            name='ho_thuc_vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.hothucvat', verbose_name='Họ thực vật'),
        ),
        migrations.CreateModel(
            name='DacDiemViPhauVaBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dac_diem_vi_phau_va_bot', models.TextField(max_length=1000, verbose_name='đặc điểm vi phẫu và bột')),
                ('duoc_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.duoclieu', verbose_name='dược liệu')),
            ],
            options={
                'verbose_name': 'đặc điểm vi phẫu và bột',
                'verbose_name_plural': 'đặc điểm vi phẫu và bột',
            },
        ),
        migrations.CreateModel(
            name='DacDiemVaPhanBo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dac_diem_va_phan_bo', models.TextField(max_length=1000, verbose_name='đặc điểm và phân bố')),
                ('duoc_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.duoclieu', verbose_name='dược liệu')),
            ],
            options={
                'verbose_name': 'đặc điểm và phân bố',
                'verbose_name_plural': 'đặc điểm và phân bố',
            },
        ),
        migrations.CreateModel(
            name='ChuY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chu_y', models.TextField(max_length=1000, verbose_name='chú ý')),
                ('duoc_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.duoclieu', verbose_name='dược liệu')),
            ],
            options={
                'verbose_name': 'chú ý',
                'verbose_name_plural': 'chú ý',
            },
        ),
        migrations.CreateModel(
            name='ChePham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('che_pham', models.TextField(max_length=1000, verbose_name='chế phẩm')),
                ('duoc_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.duoclieu', verbose_name='dược liệu')),
            ],
            options={
                'verbose_name': 'chế phẩm',
                'verbose_name_plural': 'chế phẩm',
            },
        ),
        migrations.CreateModel(
            name='CheBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('che_bien', models.TextField(max_length=1000, verbose_name='chế biến')),
                ('duoc_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.duoclieu', verbose_name='dược liệu')),
            ],
            options={
                'verbose_name': 'chế biến',
                'verbose_name_plural': 'chế biến',
            },
        ),
        migrations.CreateModel(
            name='BoPhanDung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bo_phan_dung', models.TextField(max_length=1000, verbose_name='bộ phận dùng')),
                ('duoc_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.duoclieu', verbose_name='dược liệu')),
            ],
            options={
                'verbose_name': 'bộ phận dùng',
                'verbose_name_plural': 'bộ phận dùng',
            },
        ),
    ]
