# Generated by Django 3.1.6 on 2021-03-20 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duoclieu', '0002_auto_20210320_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhomhoatchat',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, help_text='Thông tin này sẽ hiển thị tại địa chỉ web, ví dụ: www.home/duoclieu/XXXXX, nếu không nhập dữ liệu chương trình sẽ mặc định XXXXX là tên của nhóm hoạt chất.', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duoclieu',
            name='ho_thuc_vat',
            field=models.ForeignKey(help_text='Kéo chọn họ thực vật phù hợp, nếu họ thực vật chưa có ấn vào dấu + để tạo mới.', on_delete=django.db.models.deletion.CASCADE, to='duoclieu.hothucvat', verbose_name='Họ thực vật'),
        ),
        migrations.AlterField(
            model_name='duoclieu',
            name='slug',
            field=models.SlugField(help_text='Thông tin này sẽ hiển thị tại địa chỉ web, ví dụ: www.home/ho-thuc-vat/XXXXX, nếu không nhập dữ liệu chương trình sẽ mặc định XXXXX là họ dược liệu.', unique=True),
        ),
        migrations.AlterField(
            model_name='hothucvat',
            name='slug',
            field=models.SlugField(help_text='Thông tin này sẽ hiển thị tại địa chỉ web, ví dụ: www.home/duoclieu/XXXXX, nếu không nhập dữ liệu chương trình sẽ mặc định XXXXX là tên khoa học của dược liệu.', unique=True),
        ),
    ]
