# Generated by Django 3.1.6 on 2021-03-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duoclieu', '0004_auto_20210320_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duoclieu',
            name='slug',
            field=models.SlugField(help_text='Thông tin này sẽ hiển thị tại địa chỉ web, ví dụ: www.home/ho-thuc-vat/XXXXX, nếu không nhập dữ liệu chương trình sẽ mặc định XXXXX là họ dược liệu.', null=True, unique=True),
        ),
    ]
