# Generated by Django 3.1.6 on 2021-03-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duoclieu', '0006_auto_20210320_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='duoclieu',
            name='tac_dung_chinh',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Công dụng chính'),
        ),
        migrations.AlterField(
            model_name='duoclieu',
            name='nguoi_dang',
            field=models.CharField(blank=True, help_text='Tên tác giả, nếu không nhập thông tin chương trình sẽ mặc định là họ và tên của chủ tài khoản (thông tin khai báo lúc đăng ký tài khoản / tạo bởi admin).', max_length=200, null=True, verbose_name='người đăng'),
        ),
    ]
