# Generated by Django 3.1.6 on 2021-03-22 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duoclieu', '0007_auto_20210322_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de_chinh', models.CharField(max_length=200, verbose_name='tiêu đề chính')),
                ('noi_dung', models.TextField(blank=True, max_length=2000, null=True, verbose_name='nội dung')),
                ('slug', models.SlugField(allow_unicode=True, help_text='Thông tin này sẽ hiển thị tại địa chỉ web, ví dụ: www.home/duoclieu/XXXXX, với XXXX là thông tin bạn nhập vào', null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tiêu để chính',
                'verbose_name_plural': 'C. Tiêu để chính',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='level1',
            name='nhom_hoat_chat',
        ),
        migrations.DeleteModel(
            name='NhomHoatChat',
        ),
        migrations.AddField(
            model_name='level1',
            name='level_0',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='duoclieu.level0', verbose_name='<-- Level0'),
            preserve_default=False,
        ),
    ]
