# Generated by Django 3.1.6 on 2021-03-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duoclieu', '0008_auto_20210323_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='level0',
            name='nguoi_dang',
            field=models.CharField(blank=True, help_text='Tên tác giả, nếu không nhập thông tin chương trình sẽ mặc định là họ và tên của chủ tài khoản (thông tin khai báo lúc đăng ký tài khoản / tạo bởi admin).', max_length=200, null=True, verbose_name='người đăng'),
        ),
    ]
