# Generated by Django 3.1.6 on 2021-03-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duoclieu', '0009_level0_nguoi_dang'),
    ]

    operations = [
        migrations.AddField(
            model_name='hothucvat',
            name='ngay_dang',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='hothucvat',
            name='nguoi_dang',
            field=models.CharField(blank=True, help_text='Tên tác giả, nếu không nhập thông tin chương trình sẽ mặc định là họ và tên của chủ tài khoản (thông tin khai báo lúc đăng ký tài khoản / tạo bởi admin).', max_length=200, null=True, verbose_name='người đăng'),
        ),
    ]
