# Generated by Django 3.1.6 on 2021-03-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duoclieu', '0012_hinhanhlv0_hinhanhlv1_hinhanhlv2_hinhanhlv3_hinhanhlv4_hinhanhlv5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duoclieu',
            name='tac_dung_chinh',
        ),
    ]
