# Generated by Django 3.1.6 on 2021-04-18 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duoclieu', '0013_remove_duoclieu_tac_dung_chinh'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoinoiDauDL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loi_noi_dau', models.TextField(blank=True, help_text='XXXXXX', max_length=1000, null=True, verbose_name='Lời nói đầu')),
            ],
            options={
                'verbose_name': 'lời nói đầu',
                'verbose_name_plural': 'lời nói đầu',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='level0',
            name='noi_dung',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='mục tiêu'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='level_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duoclieu.level0', verbose_name='<-- Tiêu đề chính'),
        ),
        migrations.AlterField(
            model_name='level1',
            name='noi_dung',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='nội dung'),
        ),
        migrations.AlterField(
            model_name='level2',
            name='noi_dung',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='nội dung'),
        ),
        migrations.AlterField(
            model_name='level3',
            name='noi_dung',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='nội dung'),
        ),
        migrations.AlterField(
            model_name='level4',
            name='noi_dung',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='nội dung'),
        ),
        migrations.AlterField(
            model_name='level5',
            name='noi_dung',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='nội dung'),
        ),
    ]
